/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Notes {
  content: string;
  createdAt: Generated<Timestamp | null>;
  id: Generated<string>;
  tags: Generated<string[] | null>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  notes: Notes;
}




// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.